package io.github.sarveshwaredla.trycatch;

import java.util.ArrayList;

public class WriterHelper {
    public void writeList() {
	      try {
	          List<Integer> list = new ArryList<>(10);
	          list.add(1);

	          System.out.println("Entering" + " try statement");
	          Integer a = list.get(0);
	          System.out.println("accessing the first element: " + a);

	      } catch (IndexOutOfBoundsException e) {
	            System.err.println("Caught IndexOutOfBoundsException: " + e.getMessage());
	      } finally {
	            System.out.println("this will always be executed");
	      }
    }
}

Example2:

TryCatchDemo.java

package io.github.sarveshwaredla.trycatch;

public class TryCatchDemo {
    public static void main(String[] args) {
	      WriterHelper helper = new WriterHelper();
	      helper.writeList();
    }

}

Example3:

NestedTryCatch.java

package io. github.sarveshwaredla.trycatch;

public class NestedTryCatch {
    public static void main(String[] args) {

	  try{ // block 1
	    try{ // block 2
	      try{ // block 3
		        int arr[]= {1,2,3,4};

		        System.out.println(arr[10]);

	      }catch(ArrayIndexOutOfBoundsException e) {
		        System.out.println("ArrayIndexOutOfBounds Exception in block 3");
		        throw e;
	          }
	      }
	      catch(ArrayIndexOutOfBoundsException e) {
		            System.out.println("ArrayIndexOutOfBounds Exception in block 2");
		            throw e;
	          }
	      }
	      catch(ArrayIndexOutOfBoundsException e4) {
		            System.out.println("ArrayIndexOutOfBounds Exception in block 1");
	      }
	      catch(Exception e5) {
		            System.out.println("general Exception");
	      }
    }
}
